# Playstation 3 DualShock pad with a USB converter
# Test (Modus auf *Haus* umschalten): jstest /dev/input/js0
axis_linear: 1
scale_linear: 0.2
scale_linear_turbo: 0.7

axis_angular: 2
scale_angular: 0.8

enable_button: 4  # L1 shoulder button
enable_turbo_button: 5  # R1 shoulder button
